### PR TITLE
Minor updates based on feedback

### PR DESCRIPTION
**Pull request by sudeepdi**
Updates to Topics scope, timelines and Charter history table

### CODE REVIEW

**Comment by sudeepdi** [comment]
Propose file change : Updates in response to inputs from Issue #30. @dontcallmedom @DanDruta please review

**Comment by dontcallmedom** [comment]
this looks directionally right; I'm not sure what the "May 2021" timeline item is: is it a deliverable, or just discussions? if the latter, I'm concerned with not having scheduled concrete deliverables before the end of the year.

**Review by sudeepdi — COMMENTED** [review]
@Dom - the updates look fine. However, as discussed in the meeting, the "Timeline" section needs some rework. Please dont merge this. Is it possible to just merge the updates in Scope and History or I should create a separate pull request?

**Comment by dontcallmedom** [comment]
let's merge this as is, and refine the timeline in a separate pull request

**Pull request merged**
